bereshit_cont = {
    'cap_1': {
        'spanish': [
            "Por la primicia creó Elohim los cielos y la tierra",
            "Pero la tierra llegó a estar desolada° y vacía, y había tinieblas sobre la faz del abismo, y el Espíritu de Elohim se cernía sobre la faz de las aguas.",
            "Entonces dijo ’Elohim: Haya luz. Y hubo luz.",
            "Y vio ’Elohim que la luz era buena, y ’Elohim hizo separación° entre la luz y la oscuridad.",
            "Y llamó ’Elohim a la luz día y a la oscuridad llamó noche. Y fue la tarde y fue la mañana: Día uno",
            "Y dijo ’Elohim: Haya expansión en medio de las aguas y separe las aguas de las aguas.",
            "E hizo ’Elohim la expansión, y estableció separación entre las aguas que estaban debajo de la expansión y las aguas que estaban encima de la expansión. Y fue así.",
            "Y llamó ’Elohim a la expansión cielos. Y fue la tarde y fue la mañana: Día segundo.",
            "Y dijo ’Elohim: Reúnanse las aguas de debajo de los cielos en un solo lugar, y muéstrese lo seco. Y fue así",
            "Y a lo seco llamó ’Elohim tierra, y a la reunión de las aguas llamó mares. Y vio ’Elohim que estaba bien.",
            "Entonces dijo ’Elohim: Produzca la tierra vegetación: hierba que haga germinar semilla, árbol frutal que dé fruto sobre la tierra según su especie, cuya semilla esté en él. Y fue así.",
            "Y la tierra hizo brotar vegetación: hierba que hace germinar semilla según su especie, y árbol que da fruto, cuya semilla está en él, según su especie. Y vio ’Elohim que estaba bien.",
            "Y fue la tarde y fue la mañana: Día tercero.",
            "Y dijo ’Elohim: Haya lumbreras en la expansión de los cielos para diferenciar entre el día y la noche, y sirvan para señales, y para estaciones citas, y para días y años,",
            "y sean por luminarias en la expansión de los cielos para alumbrar sobre la tierra. Y fue así.",
            "E hizo ’Elohim las dos grandes lumbreras: la lumbrera mayor para regir el día, y la lumbrera menor para regir la noche.",
            "Y puso ’Elohim las estrellas en la expansión de los cielos para alumbrar sobre la tierra,",
            "y para regir durante el día y la noche, y para separar la luz de la oscuridad. Y vio ’Elohim que estaba bien.",
            "Y fue la tarde y fue la mañana: Día cuarto.",
            "Entonces dijo ’Elohim: Bullan las aguas seres vivientes y ave que vuele sobre la tierra en la expansión de los cielos.",
            "Y creó ’Elohim los grandes monstruos marinos y todo ser vivo que repta, que poblaron las aguas, según su especie, y toda ave alada según su especie. Y vio ’Elohim que estaba bien.",
            "Y ’Elohim los bendijo diciendo: Fructificad y multiplicaos, llenad las aguas en los mares y multiplíquese el ave en la tierra.",
            "Entonces dijo ’Elohim: Produzca la tierra seres vivientes según su especie: ganado, reptiles y bestias de la tierra, según su especie. Y fue así.",
            "E hizo ’Elohim las bestias de la tierra según su especie, y el ganado según su especie, y todo reptil del suelo según su especie. Y vio ’Elohim que estaba bien.",
            "Entonces dijo ’Elohim: Hagamos hombre Con nuestro resplandor, conforme a nuestra semejanza, y ejerzan dominio sobre los peces del mar, sobre las aves de los cielos, sobre el ganado, sobre toda la tierra, y sobre todo reptil que repta sobre la tierra.",
            "Y creó ’Elohim a este hombre con su resplandor, con el resplandor de ’Elohim lo creó, macho y hembra los creó.",
            "Luego ’Elohim los bendijo; y les dijo ’Elohim: Fructificad y multiplicaos, llenad la tierra y sojuzgadla, dominad sobre los peces del mar y las aves de los cielos y sobre todo ser vivo que se mueve sobre la tierra.",
            "Y dijo ’Elohim: He aquí os he dado toda hierba que produce semilla que está sobre la faz de toda la tierra, y todo árbol en el que hay fruto y que produce semilla, os será de alimento.",
            "Y a toda bestia de la tierra, y a toda ave de los cielos, y a todo lo que repta sobre la tierra, en los cuales hay vida, toda hierba verde les será por alimento. Y fue así.",
            "Y vio ’Elohim todo lo que había hecho, y he aquí estaba muy bien. Y fue la tarde y fue la mañana: El día sexto."
        ],

        'hebrew': [
            "בְּרֵאשִׁית בָּרָא אֱלֹהִים אֵת הַשָּׁמַיִם וְאֵת הָאָרֶץ",
            "וְהָאָרֶץ הָיְתָה תֹהוּ וָבֹהוּ וְחֹשֶׁךְ עַל־פְּנֵי תְהֹום וְרוּחַ אֱלֹהִים מְרַחֶפֶת עַל־פְּנֵי הַמָּיִם",
            "וַיֹּאמֶר אֱלֹהִים, יְהִי אוֹר; וַיְהִי-אוֹר",
            "וַיַּרְא אֱלֹהִים אֶת-הָאוֹר, כִּי-טוֹב; וַיַּבְדֵּל אֱלֹהִים, בֵּין הָאוֹר וּבֵין הַחֹשֶׁךְ",
            "וַיִּקְרָא אֱלֹהִים לָאוֹר יוֹם, וְלַחֹשֶׁךְ קָרָא לָיְלָה; וַיְהִי-עֶרֶב וַיְהִי-בֹקֶר, יוֹם אֶחָד",
            "וַיֹּאמֶר אֱלֹהִים, יְהִי רָקִיעַ בְּתוֹךְ הַמָּיִם, וִיהִי מַבְדִּיל, בֵּין מַיִם לָמָיִם",
            "וַיַּעַשׂ אֱלֹהִים, אֶת-הָרָקִיעַ, וַיַּבְדֵּל בֵּין הַמַּיִם אֲשֶׁר מִתַּחַת לָרָקִיעַ, וּבֵין הַמַּיִם אֲשֶׁר מֵעַל לָרָקִיעַ; וַיְהִי-כֵן",
            "וַיִּקְרָא אֱלֹהִים לָרָקִיעַ, שָׁמָיִם; וַיְהִי-עֶרֶב וַיְהִי-בֹקֶר, יוֹם שֵׁנִי",
            "וַיֹּאמֶר אֱלֹהִים, יִקָּווּ הַמַּיִם מִתַּחַת הַשָּׁמַיִם אֶל-מָקוֹם אֶחָד, וְתֵרָאֶה, הַיַּבָּשָׁה; וַיְהִי-כֵן",
            "וַיִּקְרָא אֱלֹהִים לַיַּבָּשָׁה אֶרֶץ, וּלְמִקְוֵה הַמַּיִם קָרָא יַמִּים; וַיַּרְא אֱלֹהִים, כִּי-טוֹב",
            "וַיֹּאמֶר אֱלֹהִים, תַּדְשֵׁא הָאָרֶץ דֶּשֶׁא עֵשֶׂב מַזְרִיעַ זֶרַע, עֵץ פְּרִי עֹשֶׂה פְּרִי לְמִינוֹ, אֲשֶׁר זַרְעוֹ-בוֹ עַל-הָאָרֶץ; וַיְהִי-כֵן",
            "וַתּוֹצֵא הָאָרֶץ דֶּשֶׁא עֵשֶׂב מַזְרִיעַ זֶרַע, לְמִינֵהוּ, וְעֵץ עֹשֶׂה-פְּרִי אֲשֶׁר זַרְעוֹ-בוֹ, לְמִינֵהוּ; וַיַּרְא אֱלֹהִים, כִּי-טוֹב",
            "וַיְהִי-עֶרֶב וַיְהִי-בֹקֶר, יוֹם שְׁלִישִׁי",
            "וַיֹּאמֶר אֱלֹהִים, יְהִי מְאֹרֹת בִּרְקִיעַ הַשָּׁמַיִם, לְהַבְדִּיל, בֵּין הַיּוֹם וּבֵין הַלָּיְלָה; וְהָיוּ לְאֹתֹת וּלְמוֹעֲדִים, וּלְיָמִים וְשָׁנִים",
            "וְהָיוּ לִמְאוֹרֹת בִּרְקִיעַ הַשָּׁמַיִם, לְהָאִיר עַל-הָאָרֶץ; וַיְהִי-כֵן",
            "וַיַּעַשׂ אֱלֹהִים, אֶת-שְׁנֵי הַמְּאֹרֹת הַגְּדֹלִים:  אֶת-הַמָּאוֹר הַגָּדֹל, לְמֶמְשֶׁלֶת הַיּוֹם, וְאֶת-הַמָּאוֹר הַקָּטֹן לְמֶמְשֶׁלֶת הַלַּיְלָה, וְאֵת הַכּוֹכָבִים",
            "וַיִּתֵּן אֹתָם אֱלֹהִים, בִּרְקִיעַ הַשָּׁמָיִם, לְהָאִיר, עַל-הָאָרֶץ",
            "וְלִמְשֹׁל, בַּיּוֹם וּבַלַּיְלָה, וּלְהַבְדִּיל, בֵּין הָאוֹר וּבֵין הַחֹשֶׁךְ; וַיַּרְא אֱלֹהִים, כִּי-טוֹב",
            "וַיְהִי-עֶרֶב וַיְהִי-בֹקֶר, יוֹם רְבִיעִי",
            "וַיֹּאמֶר אֱלֹהִים–יִשְׁרְצוּ הַמַּיִם, שֶׁרֶץ נֶפֶשׁ חַיָּה; וְעוֹף יְעוֹפֵף עַל-הָאָרֶץ, עַל-פְּנֵי רְקִיעַ הַשָּׁמָיִם",
            " כָּל-נֶפֶשׁ הַחַיָּה הָרֹמֶשֶׂת אֲשֶׁר שָׁרְצוּ הַמַּיִם לְמִינֵהֶם, וְאֵת כָּל-עוֹף כָּנָף לְמִינֵהוּ, וַיַּרְא אֱלֹהִים, כִּי-טוֹב",
            "וַיְבָרֶךְ אֹתָם אֱלֹהִים, לֵאמֹר:  פְּרוּ וּרְבוּ, וּמִלְאוּ אֶת-הַמַּיִם בַּיַּמִּים, וְהָעוֹף, יִרֶב בָּאָרֶץ",
            "וַיֹּאמֶר אֱלֹהִים, תּוֹצֵא הָאָרֶץ נֶפֶשׁ חַיָּה לְמִינָהּ, בְּהֵמָה וָרֶמֶשׂ וְחַיְתוֹ-אֶרֶץ, לְמִינָהּ; וַיְהִי-כֵן",
            "וַיַּעַשׂ אֱלֹהִים אֶת-חַיַּת הָאָרֶץ לְמִינָהּ, וְאֶת-הַבְּהֵמָה לְמִינָהּ, וְאֵת כָּל-רֶמֶשׂ הָאֲדָמָה, לְמִינֵהוּ; וַיַּרְא אֱלֹהִים, כִּי-טוֹב",
            "וַיֹּאמֶר אֱלֹהִים, נַעֲשֶׂה אָדָם בְּצַלְמֵנוּ כִּדְמוּתֵנוּ; וְיִרְדּוּ בִדְגַת הַיָּם וּבְעוֹף הַשָּׁמַיִם, וּבַבְּהֵמָה וּבְכָל-הָאָרֶץ, וּבְכָל-הָרֶמֶשׂ, הָרֹמֵשׂ עַל-הָאָרֶץ",
            "וַיִּבְרָא אֱלֹהִים אֶת-הָאָדָם בְּצַלְמוֹ, בְּצֶלֶם אֱלֹהִים בָּרָא אֹתוֹ:  זָכָר וּנְקֵבָה, בָּרָא אֹתָם",
            "וַיְבָרֶךְ אֹתָם, אֱלֹהִים, וַיֹּאמֶר לָהֶם אֱלֹהִים פְּרוּ וּרְבוּ וּמִלְאוּ אֶת-הָאָרֶץ, וְכִבְשֻׁהָ; וּרְדוּ בִּדְגַת הַיָּם, וּבְעוֹף הַשָּׁמַיִם, וּבְכָל-חַיָּה, הָרֹמֶשֶׂת עַל-הָאָרֶץ",
            "וַיֹּאמֶר אֱלֹהִים, הִנֵּה נָתַתִּי לָכֶם אֶת-כָּל-עֵשֶׂב זֹרֵעַ זֶרַע אֲשֶׁר עַל-פְּנֵי כָל-הָאָרֶץ, וְאֶת-כָּל-הָעֵץ אֲשֶׁר-בּוֹ פְרִי-עֵץ, זֹרֵעַ זָרַע:  לָכֶם יִהְיֶה, לְאָכְלָה",
            "וּלְכָל-חַיַּת הָאָרֶץ וּלְכָל-עוֹף הַשָּׁמַיִם וּלְכֹל רוֹמֵשׂ עַל-הָאָרֶץ, אֲשֶׁר-בּוֹ נֶפֶשׁ חַיָּה, אֶת-כָּל-יֶרֶק עֵשֶׂב, לְאָכְלָה; וַיְהִי-כֵן",
            "וַיַּרְא אֱלֹהִים אֶת-כָּל-אֲשֶׁר עָשָׂה, וְהִנֵּה-טוֹב מְאֹד; וַיְהִי-עֶרֶב וַיְהִי-בֹקֶר, יוֹם הַשִּׁשִּׁי"
        ],

        'phonetics': [
            "Bere’shit bará’ ‘Elohim ‘et hashamáyim ve’et ha’áretz",
            "Veha’áretz haytáh tohú vavohú, vejóshej al-pney tehom, verúaj Elohim merajéfet al-pney hamáyim",
            "Vayo’mer ‘Elohim: yehí ‘or, vayehí-‘or.",
            "Vayar’ ‘Elohim ‘et-ha’or ki-tov; vayavdel ‘Elohim beyn ha’or uveyn hajóshej.",
            "Vayiqrá’ ‘Elohim la-‘or yom, velajóshej qará’ laylah. Vayehí-‘érev vayehí-vóqer: yom ejad.",
            "Vayo’mer ‘Elohim: yehí raqí’a betoj hamáyim vihi mavdil beyn máyim lamáyim.",
            "Vaya’as ‘Elohim ‘et-haraqí’a, vayavdel beyn hamáyim ‘asher mitájat laraqí’a uvein hamáyim ‘asher me’al laraqí’a; vayehí-jén.",
            "Vayiqrá’ ‘Elohim la-raqí’a, shamáyim. Vayehí-‘érev vayehí-vóqer: yom shení.",
            "Vayo’mer ‘Elohim: yiqavú hamayím mitájat hashamáyim ‘el-maqóm ‘ejad, vetera’éh hayabasháh; vayehí jén.",
            "Vayiqrá ‘Elohim layabasháh, ‘éretz ulemiqvéh hamáyim qará’ yamím; vayar’ ‘Elohim ki-tov.",
            "Vayo’mer ‘Elohim: tadshé’ ha’áretz, deshe’ ‘ésev mazri’a zera’; etz pri ‘oseh prí leminó, ‘asher zar’o-vó al-ha’áretz; vayehí-jén.",
            "Vatotsé’ ha’áretz deshe’, ‘esev mazri’a zera’ leminehu, ve’etz ‘oseh prí ‘asher zar’o-vó; leminehu vayar’ ‘Elohim ki-tov.",
            "Vayehí-‘érev vayehí-vóqer: yom shlishí.",
            "Vayo’mer ‘Elohim: yehí me’orot birqí’a hashamáyim lehavdil beyn hayom uveyn halaylah, vehayú le’otot, ulemo’adím, uleyamím veshaním.",
            "Vehayú li-me’orot birqí’a hashamáyim leha’ir ‘al-ha’áretz; vayehí-jén.",
            "Vaya’as ‘Elohim ‘et-shney hame’orot hagdolim: ‘et-hama’or hagadol le-memshélet hayom, ve’et hama’or haqatón le-memshélet halai halaylah; ve’et hakojavím.",
            "Vayiten ‘otam ‘Elohim birqí’a hashamáyim, leha’ir al-ha’áretz.",
            "Velimshol bayom uvalaylah, ulehavdil beyn ha’or uveyn hajoshej; vayar’ ‘Elohim ki-tov.",
            "Vayehí-‘érev vayehí-vóqer: yom revi’í.",
            "Vayo’mer ‘Elohim yishretzú hamáyim shéretz néfesh jayáh ve’of ye’ofef al-ha’áretz al-pney reqí’a hashamáyim.",
            "Vayivrá’ ‘Elohim ‘et-hataninim hagedolim ve’et kol néfesh hajayáh haroméset, easher shartzú hamáyim le-minéhem, ve’et kol-‘of kanaf leminehú; vayar’ ‘Elohim ki-tov.",
            "Vayvárej ‘otam ‘Elohim le’mor: prú urvú umil’ú ‘et-hamáyim bayamim. Veha’of yirev ba’áretz.",
            "Vayo’mer ‘Elohim totsé’ ha’árets néfesh jayáh, lemináh behemáh varemes vejaytó-‘éretz lemináh; vayhí-jén.",
            "Vaya’ás ‘Elohim ‘et-jayat ha’áretz lemináh, ve’et-habehemáh lemináh, ve’et kol-remes ha’adamáh leminehú; vayar’ ‘Elohim ki-tov.",
            "Vayo’mer ‘Elohim: na’aséh adam betzalmenu, kidmutenu veyirdú bidgat hayam, uve’of hashamáyim, uvabehemáh, uvejol-ha’áretz, uvejol-haremes, haromes al-ha’áretz.",
            "Vayivrá’ ‘Elohim et-ha’adam betzalmó, betzelem ‘Elohim bará ‘otó, zajar uneqeváh bará’ otam.",
            "Vayvarej ‘otam ‘Elohim; vayo’mer lahem ‘Elohim: prú urevú umil’ú ‘et-ha’áretz, vejivshuha, urdú bidgat hayam, uve’of hashamáyim, uvejol-jayah haromeset ‘al-ha’aretz.",
            "Vayo’mer ‘Elohim: hinéh natati lajem ‘et-jol-‘ésev zore’a zera’, ‘asher ‘al-pney kol-ha’áretz, ve’et-kol-ha’ets ‘asher-bo fri-‘ets zore’a zara’, lajem yihyéh le-ojláh.",
            "Ulejol-jayat ha’áretz ulejol-‘of hashamáyim, ulejol romes al-ha’áretz asher-bo néfesh jayáh, et-kol-yéreq ‘ésev le’ojláh; vayhí-jén.",
            "Vayar’ ‘Elohim ‘et-kol-‘asher ‘asáh vehinéh-tov me’od vayhí-‘érev vayhí-vóqer: yom hashishí."
        ]
    },

}